src/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'top#index'
  
  resources :users
  resources :questions
end

src/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  validates :name, presence: true
  
  has_many :questions, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = 'ゲストユーザー'
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

src/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

src/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

src/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

src/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: :destroy

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません'
    end
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
    questions_path
   end
end

src/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to questions_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    questions_path
  end

end

src/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

src/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.order(id: 'DESC').page(params[:page]).per(15)
  end

  def show
    @user = User.find_by(id: params[:id])
    @questions = @user.questions.order(id: 'DESC').page(params[:page]).per(5)
  end

  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'ユーザー情報を変更しました'
    else
      render action: :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

src/app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

src/app/views/users/edit.html.erb
<div class="container login__body">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card mt-5">
        <div class="card-body">
          <h1 class="text-center">
            ユーザー情報を編集
          </h1>

          <%= form_with(model: @user, url: user_path, method: :patch, local: true) do |f| %>
          <div class="form_content my-2">
            <%= f.label :name, '名前'%>
            <%= f.text_field :name ,class: 'w-100'%>
          </div>
          <div class="form_content my-2">
            <%= f.label :email, 'メールアドレス'%>
            <%= f.text_field :email ,class: 'w-100'%>
          </div>
          <%= f.submit '編集' ,class: 'btn btn-primary w-100 submit_btn w-100 my-4'%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

src/app/views/users/index.html.erb
<div class="container user">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <ul class="user__users">
        <% @users.each do |user| %>
        <li class="user__users-item">
          <%= gravatar_for user, size: 50 %>
          <%= link_to user.name, user %>
        </li>
        <hr>
        <% end %>
      <div class="user__users-paginate">
        <%= paginate @users%>
      </div>
      </ul>
    </div>
  </div>
</div>

src/app/views/users/show.html.erb
<div class="container user__show">
  <div class="row user__show-body">
    <div class="col-lg-6">
      <div class="user__show-img">
        <%= gravatar_for @user, size: 500 %>
      </div>
    </div>
    <div class="col-lg-6 user__show-info card">
      <div class="card-body">
        <div class="user__show-info-name">
          <h1 class="user__show--info-name-label">名前</h1>
          <p>
            <%= @user.name %>
          </p>
        </div>
        <div class="user__show-info-email">
          <h1 class="user__show-info-email-label">email</h1>
          <p>
            <%= @user.email %>
          </p>
        </div>
        <div class="user__show-info-btn">
          <%= link_to 'ユーザー情報を編集', edit_user_path(@user), class: 'btn btn-outline-secondary' %>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <% if @questions.present? %>
  <div class="user__show-question">
    <h1 class="user__show-question-label my-5">投稿した問題一覧</h1>
    <% @questions.each do |q| %>
    <div class="card w-75 my-2 mx-auto">
      <div class="card-body user__show-question-body">
        <%= link_to question_path(q) do %>
        <h2>
          <%= q.title%>
        </h2>
        <div class="user__show-question-body-edit">
          <% if q.user == current_user%>
          <%= link_to '編集する', edit_question_path(q), class: 'btn btn-outline-secondary' %>
          <%= link_to '削除する', question_path(q.id), method: :delete, class: 'btn btn-outline-danger', data: {confirm: "削除しますか？"}%>
          <% end %>
          <p><%= q.created_at.strftime('%Y/%m/%d %H:%M:%S')%></p>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
    <div class="d-flex justify-content-center my-5">
      <%= paginate @questions%>
    </div>

  </div>
  <% else %>

  <div class="user__show-question">
    <h1 class="user__show-question-label my-5">投稿がありません</h1>
    <div class='text-center'>
      <%= link_to '問題を投稿する', new_question_path, class: 'btn btn-primary'%>
    </div>
  </div>
  <% end %>

</div>