src/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'top#index'
  
  resources :users
  resources :questions
end

src/app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container">
      <%= link_to 'QA-FUNC', root_path, class: 'navbar-brand' %>
      <div class="d-flex justify-content-end">
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <% if user_signed_in? %>
            <li class="nav-item mx-2">
              <%= link_to '問題を投稿', new_question_path, class: 'nav-link'%>
            </li>
            <li class="nav-item mx-2">
              <%= link_to '問題一覧', questions_path, class: 'nav-link'%>
            </li>
            <li class="nav-item mx-2">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link'%>
            </li>
            <li class="nav-item mx-2">
              <%= link_to 'ユーザー情報', user_path(current_user), class: 'nav-link'%>
            </li>
            <% else %>
            <li class="nav-item mx-2">
              <%= link_to 'ログイン', new_user_session_path, class: 'nav-link'%>
            </li>
            <li class="nav-item mx-2">
              <%= link_to '新規登録', new_user_registration_path, class: 'nav-link'%>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QAFunc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="custom__body">
      <div class="notification">
        <% flash.each do |key, value|%>
          <%= content_tag(:div, value, class: key) %>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>